name: Porter Transaction Data Processor

on:
  repository_dispatch:
    types: [porter-data]
  workflow_dispatch:

jobs:
  process-porter-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create data directory
        run: mkdir -p data/porter-transactions

      - name: Process transaction data
        run: |
          # Get current date in YYYY-MM-DD format
          CURRENT_DATE=$(date +%Y-%m-%d)

          # Create filename with timestamp
          FILENAME="data/porter-transactions/${CURRENT_DATE}.json"

          # Write the transaction data to file
          echo '${{ github.event.client_payload.data }}' > "${FILENAME}"

          # Pretty print the JSON for better readability
          if command -v jq &> /dev/null; then
            jq '.' "${FILENAME}" > "${FILENAME}.tmp" && mv "${FILENAME}.tmp" "${FILENAME}"
          fi

          # Display summary
          echo "Transaction data saved to ${FILENAME}"
          if command -v jq &> /dev/null; then
            echo "Summary:"
            jq '.summary // "No summary available"' "${FILENAME}"
          fi

      - name: Commit and push data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Porter Data Bot"
          git add data/porter-transactions/

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add Porter transaction data for $(date +%Y-%m-%d)"
            git push
            echo "Data committed and pushed successfully"
          fi

      - name: Create summary comment
        if: github.event.client_payload.data
        run: |
          echo "## Porter Transaction Data Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date +%Y-%m-%d)" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** ${{ github.event.client_payload.timestamp }}" >> $GITHUB_STEP_SUMMARY

          if command -v jq &> /dev/null && [ -f "data/porter-transactions/$(date +%Y-%m-%d).json" ]; then
            TRANSACTION_COUNT=$(jq '.transactionCount // 0' "data/porter-transactions/$(date +%Y-%m-%d).json")
            echo "**Transactions:** ${TRANSACTION_COUNT}" >> $GITHUB_STEP_SUMMARY
            
            # Add summary if available
            SUMMARY=$(jq '.summary' "data/porter-transactions/$(date +%Y-%m-%d).json" 2>/dev/null)
            if [ "$SUMMARY" != "null" ] && [ "$SUMMARY" != "" ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### Financial Summary" >> $GITHUB_STEP_SUMMARY
              echo '```json' >> $GITHUB_STEP_SUMMARY
              echo "$SUMMARY" | jq '.' >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
            fi
          fi
